# Generated by Django 5.2.1 on 2025-05-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_persona_direccion_remove_persona_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroenvio', models.IntegerField(unique=True)),
                ('peso', models.IntegerField()),
                ('nomdestinatario', models.CharField(max_length=60)),
                ('dirdestinatario', models.CharField(max_length=100)),
                ('entregado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('provincia', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerotransporte', models.IntegerField(unique=True)),
                ('fechahorasalida', models.DateTimeField()),
                ('fechahorallegada', models.DateTimeField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='gestion.sucursal')),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='paquete',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='gestion.repartidor'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartidores', to='gestion.sucursal'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='gestion.sucursal'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='gestion.transporte'),
        ),
    ]
