# Generated by Django 5.2.1 on 2025-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_paquete_repartidor_sucursal_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='fechahorallegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
